# docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: beta
    schedule:
      interval: monthly
      timezone: US/Michigan
      time: '06:00'
    groups:
      github_actions:
        patterns:
          - '*'
    versioning-strategy: increase

  - package-ecosystem: npm
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
      day: sunday
      timezone: US/Michigan
      time: '06:00'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
    versioning-strategy: widen
